sudo: false
language: python
env:
  global:
  - secure: BsHcolRQHHRUWT3R0fGty66LSnq9lMg0shuGUr0FD5geyf3pHwnO/upYtahfF8cQBUVjX3SARioZSQj+NlFtBM6LiuA5K5wuV13ziHc0Klcy2SiFEu5WXi+GoVFbgiAx9cgYYcLTlI/K1UYV+xWLZ0etyYAybo4hbf4WM5BHGWxz+909Q2AJ39NctM5oy1aswl3Dp4pSvUGIzDR5vkAy+CMPAAkDbWbtqc/l0Nh1FB+k6vjd2XdfaSvqZEGAQSlRob8OTSYktNmPrZ9cNLnH+4QIgOxyb1HgyzCW2aUHkoNczf6mUJpbmXAtFTUx88Lwg7oCGYbAT3vObymJ88ENzZ1I9dSUsQ/2AO/fonSwy/8/FlRwKzEJqYu+7ArAOWMfSP23/EyDv1BYoGNtfstGnZ0ySUf6h/OR7CNg4bcfJchANiK7Pz8cxQkZA2xunZe48dnmdOkqoGSAymYDNzIAxRTYuPWprkj7XKhAf4sm0YqsfslxOR6D6Q4W9XYHARd3CWEBA8+7/WMv4COQpoNhss+FGMPHg44/3KeEG6nXuoT/r/b+Ns9H/TB5xziNVsVKzJxoN4c3JSMvGM0zHO1oTz5lNyTRqkU/yINKxPQJyDay0y7Xr8grY3hWXFAz0Y55uZ48Iq2T7to2Wp4SOErB+rLAjoD/wzdmTIN+gHKAPAk=
  - secure: i2Qlvkl+PqHRx79rP6fJxuV07KMxk72jZogf6CuQVQRg/N8J0yJUxs4L5t0BngEunEH9jTPtVbsRudfXqo7r4vBB6mq9o72a8EygzZw6JrTEiixjTJxb4/m3D7yntx9F/ioxWLumKCn0iBP765KpBJc8qzRwWOHc+qadY33t3/mwizYJBauh293NOR1ipa/pomgEarjt7oCgcKxhSKQoj+uFLXMOXYsqAyNaOa9Tyiw+EA6UgEy9R+YIt2QhOznXl8NzYWwfp91+pbERgHKvXrQEyuothtdULBH/DDNkvIJCKLp1lv/Rr9A7Ao2Sso9uWItcIKnR/QvgL361HtvI3qqva/JXwdLj6TVRCO3kIgR+pnCHA1MkkBRX56PaoTTtwpaMsbUeneXhm+Bvr4kV2gFdgZOsbpJXCohCYdjdHzlRQVI5vi7jK2Qi9z2z1GeAuLFvpyjTeEJvnOrl3ZHPs42ReAZon3PzmhJXF/rqntM/5LF2UKskQwBMdEHvB4jyIwZJ30agYTO4hzQDBPkz25FqFy182mwnwYZTPsZMYwKaYo70+MehoObZBOxFELZbsrtKxl6oHtwEQgVLgGSnjSR3B3NInrZRp4W1BeTEJ+ofO9nJmu9fz/zsEicvdRVir+mwzqOBIE9TgOVWOcUfDfP0agyPgvWk4ZyWXuDlMHo=
  - secure: IPZOW5Af4RnY2UQV771O9x8YC5RXLqxPHiKjiEdBEN1nwzxoDC/K4TG5Ho0BvBcUOR+CwDwfD3ESzHeSvtAs1wCXQsvcqG7TZ10eSOc/e8A/h1cMLMOexzyrsUrkAV+B+521FnhoATSazHdAkx9xLkFzW2NNO2uw/jEY/hVKjge3ajYevCNf2fuawX0vmBwf3xqnDuFT5/owejkT9KNj3G2MW0ONnsa1Klo/Z6KOJV8tv6zDYblwmWqCNCFxzF0QRcGBMKLmGr5ktr9YQsqgK+qUSujMbMHmiwa1R2X/BQCxu9Gaw45QuNHVakhZW0xggzRw0iqQgSEeasht+QWoNnOkeQQ/mrHWYPPzqFYJXbaDyPxhzIDtBca+7OItyBDBwe5+bgCJLqhnUJUM0JyXFq3aa+9YOQOUWxObNNUbEMP+USwGPqGiiOocDnBFKITlfz5Yu7g1KpPtZAarD88dpSJDY22KimTpmY/p19TXI1HSP7hBgJhCfWszL1bEzeSNzLZPJsUNnShPbcnZEYE0UDY5CA8qKmQph31sUeBVe4MleItl+3fwnNt6wEwxlVhsrIKphbtQDL7nYHFnRKqCA1QHuo6v6YoLWQzQYd3WhEo1nMp9yeC7cagC6GCIERE9IggDTGQThSqu9wBQMqZDdgkOlOebjE9qzPl9JRZsvOI=
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda env create -f environment.yml
- source activate pydi
script:
- coverage run test.py
after_success:
- coveralls

