name: pydi
channels:
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - ca-certificates=2017.08.26
  - certifi=2018.1.18
  - cffi=1.11.5
  - chardet=3.0.4
  - cryptography=2.1.4
  - decorator=4.2.1
  - idna=2.6
  - ipython=6.2.1
  - ipython_genutils=0.2.0
  - jedi=0.11.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1
  - libffi=3.2.1
  - ncurses=6.0
  - openssl=1.0.2n
  - parso=0.1.1
  - pexpect=4.4.0
  - pickleshare=0.7.4
  - pip=9.0.1
  - prompt_toolkit=1.0.15
  - ptyprocess=0.5.2
  - pycparser=2.18
  - pygments=2.2.0
  - pyopenssl=17.5.0
  - pysocks=1.6.8
  - python=3.6.4
  - readline=7.0
  - requests=2.18.4
  - setuptools=38.5.1
  - simplegeneric=0.8.1
  - six=1.11.0
  - sqlite=3.22.0
  - tk=8.6.7
  - traitlets=4.3.2
  - urllib3=1.22
  - wcwidth=0.1.7
  - wheel=0.30.0
  - xz=5.2.3
  - zlib=1.2.11
  - pip:
    - coverage==4.5.1
    - nose2==0.7.4
