name: pydi
channels:
  - defaults
dependencies:
  - python=3.6.4
  - requests=2.18.4
  - pip:
    - coverage==4.5.1
    - nose2==0.7.4
    - coveralls==1.3.0
    - sphinx==1.7.1
    - sphinx-autobuild==0.7.1
